# Generated by Django 4.2.17 on 2026-05-14 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_timeslot_timetable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentguardian',
            name='relationship',
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
