# Generated by Django 4.2.17 on 2026-05-14 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_remove_studentguardian_relationship_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='staff_criteria',
            field=models.CharField(choices=[('employee', 'Employee'), ('transfer', 'Transfer')], default='employee', max_length=20),
        ),
        migrations.AddField(
            model_name='staff',
            name='transfer_from',
            field=models.CharField(blank=True, choices=[('school', 'School'), ('bureau', 'Bureau')], max_length=20, null=True),
        ),
    ]
