# Generated by Django 4.2.17 on 2026-05-14 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_studyschedule_marksplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTeacherFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '⭐ Poor'), (2, '⭐⭐ Fair'), (3, '⭐⭐⭐ Good'), (4, '⭐⭐⭐⭐ Very Good'), (5, '⭐⭐⭐⭐⭐ Excellent')], default=3)),
                ('category', models.CharField(choices=[('teaching', 'Teaching Quality'), ('communication', 'Communication'), ('support', 'Student Support'), ('punctuality', 'Punctuality'), ('other', 'Other')], default='teaching', max_length=20)),
                ('message', models.TextField()),
                ('is_anonymous', models.BooleanField(default=False)),
                ('reply', models.TextField(blank=True, default='')),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_feedbacks', to='main_app.staff')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_feedbacks', to='main_app.student')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_feedbacks', to='main_app.subject')),
            ],
            options={
                'verbose_name': 'Student→Teacher Feedback',
                'ordering': ['-created_at'],
            },
        ),
    ]
